# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, help_text='根据name生成的，用于生成页面url，必须唯一', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
