# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
