# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0008_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(default='nothing', max_length=255)),
                ('max_member_nums', models.IntegerField(default=200)),
                ('admins', models.ManyToManyField(related_name='group_admins', to='web.UserProfile')),
                ('members', models.ManyToManyField(blank=True, to='web.UserProfile')),
            ],
        ),
    ]
